### ISSUE TITLE
Hi, Dear SunHowe. How to use it?  I didnt see any MenuItem?

### ISSUE THREAD

**Issue by defchen** [SunHowe/FairyGUI-CodeGenerator#1]
Hi, Dear SunHowe. How to use it?  I didnt see any MenuItem?

**Comment by SunHowe** [comment]
Hello, I will upload a sample later

**Comment by SunHowe** [comment]
> Hi, Dear SunHowe. How to use it? I didnt see any MenuItem?

Hello, I submitted a reference using the sample Example.unitypackage, you can see this git commit [38aa00296e809c2045a60bc5819d6c1e3572b487](https://github.com/SunHowe/FairyGUI-CodeGenerator/commit/38aa00296e809c2045a60bc5819d6c1e3572b487)
